version: "3.8"

services:
    client:
        build:
          context: /client/
        ports:
          - "4200:4200"
        depends_on:
          - nodeapi
          - javaapi

    javaapi:
        build:
          context: /javaapi/
        ports:
          - "9000:9000"
        depends_on:
          - mysql

    nodeapi:
        build:
          context: /nodeapi/
        ports:
          - "5000:5000"
        depends_on:
          - nginx
          - mongo
    
    nginx:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        restart: always

    mongo:
        image: mongo:4
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_ DATABASE=epoc
          
    mysql: 
        image: mysql:8.0.33
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=emartdbpass
          - MYSQL_DATABASE=books
          
